//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureParcel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureParcel.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent and guaranteed payment for the delivery of goods using Credits blockchain.
        /// </summary>
        public static string Account_Login_Block1_Text_1_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block1_Text_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to Blockchain, Escrow service works in a transparent and decentralized way. No one will be able to interrupt the operation, or cancel..
        /// </summary>
        public static string Account_Login_Block1_Text_1_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block1_Text_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string Account_Login_Block1_Text_2_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block1_Text_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user?.
        /// </summary>
        public static string Account_Login_Block1_Text_2_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block1_Text_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal protection.
        /// </summary>
        public static string Account_Login_Block2_Text_1_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain acts as a guarantor of payment for delivery.
        /// </summary>
        public static string Account_Login_Block2_Text_1_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save money.
        /// </summary>
        public static string Account_Login_Block2_Text_2_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost-effective solutions for bundling business processes of companies.
        /// </summary>
        public static string Account_Login_Block2_Text_2_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Account_Login_Block2_Text_3_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain is a “robot” that works independently.
        /// </summary>
        public static string Account_Login_Block2_Text_3_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block2_Text_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob decides to buy goods from Alice. Alice’s location is unknown to Bob. Bob is worried about how safely the transaction can be conducted. What if Alice receives the money, but decides not to send the goods to Bob?.
        /// </summary>
        public static string Account_Login_Block3_Text_1_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block3_Text_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best option for Bob to protect himself, is by using an escrow account on the blockchain..
        /// </summary>
        public static string Account_Login_Block3_Text_1_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block3_Text_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain escrow is the ability to use smart contracts and the Credits blockchain account system for safe payments between the buyer and seller. Smart contracts make it possible to automate the onset of transfers from one owner to another upon the occurrence of certain conditions: receipt of goods by the buyer upon delivery of goods via DHL..
        /// </summary>
        public static string Account_Login_Block3_Text_2_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block3_Text_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob the buyer pays the money, and Alice the seller can receive it when he fulfills the conditions previously prescribed in the blockchain smart contract. Blockchain acts as a third-party decentralized system that automatically monitors these conditions without any involvement of a person, or company..
        /// </summary>
        public static string Account_Login_Block3_Text_3_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block3_Text_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is escrow service needed?.
        /// </summary>
        public static string Account_Login_Block3_Text_Title {
            get {
                return ResourceManager.GetString("Account_Login_Block3_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern solution.
        /// </summary>
        public static string Account_Login_Block4_Text_1_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blockchain market is projected to reach $3.1 trillion by 2030..
        /// </summary>
        public static string Account_Login_Block4_Text_1_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery of all goods.
        /// </summary>
        public static string Account_Login_Block4_Text_2_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide variety of choices. From food to containers..
        /// </summary>
        public static string Account_Login_Block4_Text_2_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible integration systems.
        /// </summary>
        public static string Account_Login_Block4_Text_3_1 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart contracts enable flexible customization.
        /// </summary>
        public static string Account_Login_Block4_Text_3_2 {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Now.
        /// </summary>
        public static string Account_Login_Block4_Text_Title {
            get {
                return ResourceManager.GetString("Account_Login_Block4_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will appreciate the convenience of the service.
        /// </summary>
        public static string Account_Login_Block5_Text_Title {
            get {
                return ResourceManager.GetString("Account_Login_Block5_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BTN_Close {
            get {
                return ResourceManager.GetString("BTN_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue reading.
        /// </summary>
        public static string BTN_Continue_reading {
            get {
                return ResourceManager.GetString("BTN_Continue_reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string BTN_Remember_me {
            get {
                return ResourceManager.GetString("BTN_Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send parcel.
        /// </summary>
        public static string BTN_Send_parcel {
            get {
                return ResourceManager.GetString("BTN_Send_parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string BTN_Sign_in {
            get {
                return ResourceManager.GetString("BTN_Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string BTN_Sign_up {
            get {
                return ResourceManager.GetString("BTN_Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Demo_Account {
            get {
                return ResourceManager.GetString("Demo_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Demo_Address {
            get {
                return ResourceManager.GetString("Demo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Demo_Comments {
            get {
                return ResourceManager.GetString("Demo_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation of cost and registration of an order.
        /// </summary>
        public static string Demo_Comments_Text {
            get {
                return ResourceManager.GetString("Demo_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost , (cs).
        /// </summary>
        public static string Demo_Cost_cs {
            get {
                return ResourceManager.GetString("Demo_Cost_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of departure.
        /// </summary>
        public static string Demo_Date_of_departure {
            get {
                return ResourceManager.GetString("Demo_Date_of_departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment.
        /// </summary>
        public static string Demo_Date_of_payment {
            get {
                return ResourceManager.GetString("Demo_Date_of_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Demo_Delivered {
            get {
                return ResourceManager.GetString("Demo_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Demo_Delivery {
            get {
                return ResourceManager.GetString("Demo_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery failure.
        /// </summary>
        public static string Demo_Delivery_failure {
            get {
                return ResourceManager.GetString("Demo_Delivery_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string Demo_Delivery_Status {
            get {
                return ResourceManager.GetString("Demo_Delivery_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En route.
        /// </summary>
        public static string Demo_En_route {
            get {
                return ResourceManager.GetString("Demo_En_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Demo_Invoice {
            get {
                return ResourceManager.GetString("Demo_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string Demo_More_information {
            get {
                return ResourceManager.GetString("Demo_More information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Demo_Name {
            get {
                return ResourceManager.GetString("Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string Demo_Next_Step {
            get {
                return ResourceManager.GetString("Demo_Next_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Delivered.
        /// </summary>
        public static string Demo_Not_Delivered {
            get {
                return ResourceManager.GetString("Demo_Not_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not paid.
        /// </summary>
        public static string Demo_Not_paid {
            get {
                return ResourceManager.GetString("Demo_Not_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sent.
        /// </summary>
        public static string Demo_Not_Sent {
            get {
                return ResourceManager.GetString("Demo_Not_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Demo_Paid {
            get {
                return ResourceManager.GetString("Demo_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Demo_Pay {
            get {
                return ResourceManager.GetString("Demo_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Demo_Payment {
            get {
                return ResourceManager.GetString("Demo_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous step.
        /// </summary>
        public static string Demo_Previous_step {
            get {
                return ResourceManager.GetString("Demo_Previous_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string Demo_Public_Key {
            get {
                return ResourceManager.GetString("Demo_Public_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Demo_Receiver {
            get {
                return ResourceManager.GetString("Demo_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver&apos;s Portal.
        /// </summary>
        public static string Demo_Receivers_Portal {
            get {
                return ResourceManager.GetString("Demo_Receivers_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Demo_Sender {
            get {
                return ResourceManager.GetString("Demo_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender&apos;s Portal.
        /// </summary>
        public static string Demo_Senders_Portal {
            get {
                return ResourceManager.GetString("Demo_Senders_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking number.
        /// </summary>
        public static string Demo_Tracking_number {
            get {
                return ResourceManager.GetString("Demo_Tracking_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escrow.
        /// </summary>
        public static string Nav_Escrow {
            get {
                return ResourceManager.GetString("Nav_Escrow", resourceCulture);
            }
        }
    }
}
