//using Credtis_Api_Connect;
//using Credtis_Api_Connect.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SecureParcel.Classes
{
    public class SmartContract
    {
        public static void Deploy(string SenderPublicKey = "6msdfZdDj9nwRGuDBoyUFRaXnP7tmG117BPx7tdvUjsm")
        {
            try
            {
                //using (Work work = new Work("89.111.33.169"))
                //{
                //    var transaction = work.Api.SendTransaction<CreateTransactionModel>(new CreateTransactionModel(new TransactionCreateModel
                //    {
                //        Amount = "0",
                //        Fee = "0.9",
                //        Source = SenderPublicKey,
                //        Smart = new SmartCreateModel
                //        {
                //            Code = "package com.credits.smartcontracts;"
                //            + "import com.credits.scapi.annotations.Getter;"
                //            + "import com.credits.scapi.v2.SmartContract;"
                //            + "import com.google.gson.Gson;"
                //            + ""
                //            + "import java.io.Serializable;"
                //            + "import java.math.BigDecimal;"
                //            + "import java.nio.charset.StandardCharsets;"
                //            + "import java.util.*;"
                //            + ""
                //            + "public class Dhl extends SmartContract"
                //            + "{"
                //            + "    private Map<String, Data> dataMap = new HashMap<>();"
                //            + "        private String owner;"
                //            + ""
                //            + "        public Dhl()"
                //            + "        {"
                //            + "            super();"
                //            + "            owner = initiator;"
                //            + "        }"
                //            + ""
                //            + "        protected String toJson(Object object)"
                //            + "        {"
                //            + "            return new Gson().toJson(object);"
                //            + "        }"
                //            + ""
                //            + "        private void checkPermission() throws DhlException"
                //            + "        {"
                //            + "        if (!initiator.equals(owner)) {"
                //            + "            throw new DhlException(\"403 Permission denied\");"
                //            + "    }"
                //            + "}"
                //            + ""
                //            + "public void transferAmountToOwner(double amount) throws DhlException"
                //            + "{"
                //            + "    checkPermission();"
                //            + "    sendTransaction(contractAddress, owner, amount);"
                //            + "}"
                //            + ""
                //            + "public String sendAmountToSender()"
                //            + "{"
                //            + "    Response response;"
                //            + "    try"
                //            + "    {"
                //            + "        checkPermission();"
                //            + "        Data data = dataMap.get(initiator);"
                //            + "        if (dataMap == null)"
                //            + "        {"
                //            + "            response = new Response(1, \"Data is not found\");"
                //            + "        }"
                //            + "        else"
                //            + "        {"
                //            + "            sendTransaction(contractAddress, data.getSender(), data.getAmount());"
                //            + "            response = new Response(0, \"\");"
                //            + "        }"
                //            + "    }"
                //            + "    catch (DhlException e)"
                //            + "    {"
                //            + "        response = new Response(1, e.getMessage());"
                //            + "    }"
                //            + "    return toJson(response);"
                //            + "}"
                //            + ""
                //            + "public String returnAmountToReceiver()"
                //            + "{"
                //            + "    Response response;"
                //            + "    try"
                //            + "    {"
                //            + "        checkPermission();"
                //            + "        Data data = dataMap.get(initiator);"
                //            + "        if (dataMap == null)"
                //            + "        {"
                //            + "            response = new Response(1, \"Data is not found\");"
                //            + "        }"
                //            + "        else"
                //            + "        {"
                //            + "            sendTransaction(contractAddress, data.getReceiver(), data.getAmount());"
                //            + "            response = new Response(0, \"\");"
                //            + "        }"
                //            + "    }"
                //            + "    catch (DhlException e)"
                //            + "    {"
                //            + "        response = new Response(1, e.getMessage());"
                //            + "    }"
                //            + "    return toJson(response);"
                //            + "}"
                //            + ""
                //            + ""
                //            + "@Getter"
                //            + "    public double getContractBalance() throws DhlException"
                //            + "{"
                //            + "    checkPermission();"
                //            + "        return getBalance(contractAddress).doubleValue();"
                //            + "}"
                //            + ""
                //            + "public String payable(BigDecimal amount, byte[] userData)"
                //            + "{"
                //            + "    UserDataInput userDataInput = new Gson().fromJson(new String(userData, StandardCharsets.UTF_8), UserDataInput.class);"
                //            + "        dataMap.put(initiator, new Data("
                //            + "                userDataInput.getSender(),"
                //            + "                userDataInput.getReceiver(),"
                //            + "                amount.doubleValue()"
                //            + "        ));"
                //            + ""
                //            + "        Response response = new Response(0, \"\");"
                //            + "        return toJson(response);"
                //            + "    }"
                //            + ""
                //            + "    static class UserDataInput implements Serializable"
                //            + "{"
                //            + "private String sender;"
                //            + "private String receiver;"
                //            + ""
                //            + "public UserDataInput(String sender, String receiver)"
                //            + "{"
                //            + "    this.sender = sender;"
                //            + "    this.receiver = receiver;"
                //            + "}"
                //            + ""
                //            + "public String getSender()"
                //            + "{"
                //            + "    return sender;"
                //            + "}"
                //            + ""
                //            + "public String getReceiver()"
                //            + "{"
                //            + "    return receiver;"
                //            + "}"
                //            + "}"
                //            + ""
                //            + "static class Data implements Serializable"
                //            + "{"
                //            + "private String sender;"
                //            + "private String receiver;"
                //            + "private double amount;"
                //            + "public Data() { }"
                //            + ""
                //            + "public Data(String sender, String receiver, double amount)"
                //            + "{"
                //            + "    this.sender = sender;"
                //            + "    this.receiver = receiver;"
                //            + "    this.amount = amount;"
                //            + "}"
                //            + ""
                //            + "public String getSender()"
                //            + "{"
                //            + "    return sender;"
                //            + "}"
                //            + ""
                //            + "public String getReceiver()"
                //            + "{"
                //            + "    return receiver;"
                //            + "}"
                //            + ""
                //            + "public double getAmount()"
                //            + "{"
                //            + "    return amount;"
                //            + "}"
                //            + "}"
                //            + ""
                //            + "static class Response implements Serializable"
                //            + "{"
                //            + "private int code;"
                //            + "private String errorMessage;"
                //            + ""
                //            + "public Response(int code, String errorMessage)"
                //            + "{"
                //            + "    this.code = code;"
                //            + "    this.errorMessage = errorMessage;"
                //            + "}"
                //            + "}"
                //            + ""
                //            + "    static class DhlException extends Exception"
                //            + "    {"
                //            + "         DhlException(String message) {"
                //            + "         super(message);"
                //            + "     }"
                //            + "}"
                //            + ""
                //            + "}"
                //        }
                //    }), Base58Check.Base58CheckEncoding.DecodePlain("54tZoXaDa38n8rbg1BGrDMVBSP12TGcyE7UNvDQfD7w1uEMYCzdv7bpDycgiPwNd92opbZh94kVmArVoW4YFDF4j"));

                //    var source = transaction.Source;
                //}
            }
            catch (Exception err)
            {
                var msg = err.ToString();
            }
        }
    }
}